name: openmptcprouter
on: 
  workflow_dispatch:
    inputs:
      omr_target:
        description: 'OMR Target (leave empty for all)'
        required: false
        type: string
      omr_kernel:
        description: 'OMR Kernel version'
        required: true
        type: choice
        options:
          - '6.6'
          - '6.12'
        default: '6.6'

env:
  REPO_URL: 'https://github.com/InterfaceGUI/openmptcprouter'

jobs:
  build:
    strategy:
      matrix:
        OMR_TARGET: [x86_64]
        OMR_KERNEL: [6.12]
        exclude:
          - OMR_KERNEL: ${{ github.event.inputs.omr_kernel != '6.6' && '6.6' || 'none' }}
          - OMR_KERNEL: ${{ github.event.inputs.omr_kernel != '6.12' && '6.12' || 'none' }}
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - name: Branch name
      id: branch_name
      run: |
        echo "SOURCE_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
        echo "SOURCE_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        echo "SOURCE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        echo "WORKSPACE=${GITHUB_WORKSPACE}" >> $GITHUB_OUTPUT
        
    - name: Prepare
      run: |
        sudo apt-get update
        sudo apt-get install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc-s1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler python3-pyelftools llvm clang
        
    - if: matrix.OMR_KERNEL == '6.6'
      name: Install LLVM
      run: |
        sudo apt-get install llvm clang
        
    - name: Free disk space
      run: |
        df -h
        sudo swapoff -a >/dev/null 2>&1 || true
        sudo rm -f /swapfile >/dev/null 2>&1 || true
        sudo apt-get autoremove -y >/dev/null 2>&1 || true
        sudo apt-get autoclean -y >/dev/null 2>&1 || true
        sudo rm -rf "/usr/local/share/boost" >/dev/null 2>&1 || true
        sudo rm -rf "$AGENT_TOOLSDIRECTORY" >/dev/null 2>&1 || true
        sudo rm -rf /usr/share/dotnet >/dev/null 2>&1 || true
        sudo rm -rf /usr/local/lib/android >/dev/null 2>&1 || true
        sudo rm -rf /opt/ghc >/dev/null 2>&1 || true
        sudo docker rmi $(docker images -qf "dangling=true") >/dev/null 2>&1 || true
        df -h
        
    - name: Clone source code
      working-directory: ../../
      env: 
        REPO_URL: https://github.com/ysurac/openmptcprouter
        SOURCE_NAME: ${{ steps.branch_name.outputs.SOURCE_NAME }}
        GITHUB_WORKSPACE: ${{ steps.branch_name.outputs.WORKSPACE }}
      run: |
        git clone $REPO_URL omr
        if [ "$SOURCE_NAME" != "develop" ]; then
          cd omr
          pwd
          git fetch
          git checkout master
        else
          cd omr
          git checkout develop
        fi
        git pull
        pwd
        
    - name: Build toolchain
      working-directory: ../../omr
      env:
        OMR_FEED_URL: https://github.com/ysurac/openmptcprouter-feeds
        SOURCE_NAME: ${{ steps.branch_name.outputs.SOURCE_NAME }}
        OMR_TARGET: ${{ matrix.OMR_TARGET }}
        OMR_KERNEL: ${{ matrix.OMR_KERNEL }}
      run: |
        OMR_KERNEL="${OMR_KERNEL}" OMR_FEED_SRC="${SOURCE_NAME}" sh build.sh prepare {tools,toolchain}/install -j$(nproc) || OMR_KERNEL="${OMR_KERNEL}" OMR_FEED_SRC="${SOURCE_NAME}" sh build.sh prepare {tools,toolchain}/install -j$(nproc) V=s
    
    
    - name: Apply custom config
      working-directory: ../../omr
      env:
        OMR_TARGET: ${{ matrix.OMR_TARGET }}
        OMR_KERNEL: ${{ matrix.OMR_KERNEL }}
      run: |
        cp ${{ github.workspace }}/custom.config $OMR_TARGET/$OMR_KERNEL/source/.config
        make -C $OMR_TARGET/$OMR_KERNEL/source defconfig

        
    - name: Build packages
      working-directory: ../../omr
      env:
        OMR_TARGET: ${{ matrix.OMR_TARGET }}
        OMR_KERNEL: ${{ matrix.OMR_KERNEL }}
      run: |
        make IGNORE_ERRORS=m -C $OMR_TARGET/$OMR_KERNEL/source package/{compile,install,index} -j$(nproc) || make IGNORE_ERRORS=m -C $OMR_TARGET/$OMR_KERNEL/source package/{compile,install,index} -j$(nproc) V=s
        
    - name: Build image
      working-directory: ../../omr
      env:
        OMR_TARGET: ${{ matrix.OMR_TARGET }}
        OMR_KERNEL: ${{ matrix.OMR_KERNEL }}
      run: |
        make IGNORE_ERRORS=m -C $OMR_TARGET/$OMR_KERNEL/source target/install -j$(nproc) || make IGNORE_ERRORS=m -C $OMR_TARGET/$OMR_KERNEL/source target/install -j$(nproc) V=s
        
    - name: Compress artifacts
      run: |
        cd /home/runner/work/omr/${{ matrix.OMR_TARGET }}/${{ matrix.OMR_KERNEL }}
        tar -I 'zstd -T0 -19' -cvf source.tar.zst source
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.OMR_TARGET }}-kernel-${{ matrix.OMR_KERNEL }}-project
        path: /home/runner/work/omr/${{ matrix.OMR_TARGET }}/${{ matrix.OMR_KERNEL }}/source.tar.zst
        retention-days: 30

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.OMR_TARGET }}-kernel-${{ matrix.OMR_KERNEL }}-bin
        path: /home/runner/work/omr/${{ matrix.OMR_TARGET }}/${{ matrix.OMR_KERNEL }}/source/bin
        retention-days: 30
